/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PollingSystem;
import java.awt.Color;
import javax.swing.*;
import javax.swing.event.*;

/**
 *
 * @author KenweiVI
 */
public class CreatePoll extends javax.swing.JFrame implements CaretListener {
    
    JPanel jPanelPollInfo;
    /**
     * Creates new form CreatePoll
     */
    public CreatePoll() {
        initComponents();
        jPanelPollInfo = new JPanel();
        
        setLayout(null);
        jPanelPollInfo.setBounds(200, 300, 1000, 800);
        jPanelPollInfo.setOpaque(true);
        
        //uncomment to see dynamically created jpanel area
        //jPanelPollInfo.setBackground(Color.CYAN);
        
        jTextFieldPollSize.addCaretListener(this);
        
        add(jPanelPollInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButtonHomePage2 = new javax.swing.JButton();
        jButtonSignOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPollSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 800));

        jButtonHomePage2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonHomePage2.setText("Home Page");
        jButtonHomePage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomePage2ActionPerformed(evt);
            }
        });

        jButtonSignOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSignOut.setText("Signout");
        jButtonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignOutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Poll Size:");

        jTextFieldPollSize.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldPollSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPollSizeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("(Max 10)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(938, Short.MAX_VALUE)
                .addComponent(jButtonHomePage2)
                .addGap(18, 18, 18)
                .addComponent(jButtonSignOut)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPollSize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSignOut)
                    .addComponent(jButtonHomePage2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPollSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 535, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Create A New Poll userName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1)
                .addContainerGap(438, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomePage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomePage2ActionPerformed
        // TODO add your handling code here:
        HomePage Info = new HomePage();
        dispose();
        Info.setVisible(true);
    }//GEN-LAST:event_jButtonHomePage2ActionPerformed

    private void jButtonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignOutActionPerformed
        // TODO add your handling code here:
        LoginWindow Info = new LoginWindow();
        dispose();
        Info.setVisible(true);
    }//GEN-LAST:event_jButtonSignOutActionPerformed

    private void jTextFieldPollSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPollSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPollSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePoll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHomePage2;
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldPollSize;
    // End of variables declaration//GEN-END:variables


    @Override
    public void caretUpdate(CaretEvent e) {
        String pollSize = jTextFieldPollSize.getText();
        
        jPanelPollInfo.removeAll();
        
        if(!pollSize.equals("")) {
            int pollSizeInt = Integer.parseInt(pollSize);
            int answers = 0;                    
            
            if (pollSizeInt <= 10 ) {                
                JLabel jlabelPollName = new JLabel();
                JTextField jtextfieldPollName = new JTextField();
                               
                
                JLabel jlabels[] = new JLabel[pollSizeInt];
                JTextField jtextfields[] = new JTextField[pollSizeInt];
                
                
                JLabel jlabelanswers[] = new JLabel[pollSizeInt];
                JTextField jtextfieldanswers[] = new JTextField[pollSizeInt];
                
                
                jlabelPollName.setText("Poll Name: ");
                jlabelPollName.setFont(new java.awt.Font("Tahoma", 1, 24));
                jlabelPollName.setPreferredSize(new java.awt.Dimension(400, 40));
                jlabelPollName.setHorizontalAlignment(JLabel.RIGHT);
                jPanelPollInfo.add(jlabelPollName);
                
                
                jtextfieldPollName.setFont(new java.awt.Font("Tahoma", 1, 24));
                jtextfieldPollName.setPreferredSize(new java.awt.Dimension(400, 40));
                jPanelPollInfo.add(jtextfieldPollName);
                for (int i = 0; i < jlabels.length; i++) {
                    jlabels[i] = new JLabel("Q" + i);
                    jlabels[i].setText("Question " + (i+1) + ": ");
                    jlabels[i].setFont(new java.awt.Font("Tahoma", 1, 24));
                    jlabels[i].setPreferredSize(new java.awt.Dimension(200, 40));
                    jPanelPollInfo.add(jlabels[i]);
                    
                    jtextfields[i] = new JTextField();
                    jtextfields[i].setFont(new java.awt.Font("Tahoma", 1, 24));
                    jtextfields[i].setPreferredSize(new java.awt.Dimension(200, 40));
                    jPanelPollInfo.add(jtextfields[i]);
                    
                    jlabelanswers[i] = new JLabel("Q" + i);
                    jlabelanswers[i].setText("Q" + (i+1) + " Answer #: ");
                    jlabelanswers[i].setFont(new java.awt.Font("Tahoma", 1, 24));
                    jlabelanswers[i].setPreferredSize(new java.awt.Dimension(200, 40));
                    jPanelPollInfo.add(jlabelanswers[i]);
                    
                    jtextfieldanswers[i] = new JTextField();
                    jtextfieldanswers[i].setFont(new java.awt.Font("Tahoma", 1, 24));
                    jtextfieldanswers[i].setPreferredSize(new java.awt.Dimension(200, 40));
                    jPanelPollInfo.add(jtextfieldanswers[i]);
                    
                    //WIP
                    //jtextfieldanswers[i].addCaretListener(this);
                    
                    
                }
            }
        }          
        jPanelPollInfo.validate();
        jPanelPollInfo.repaint();
    }
}
