/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PollingSystem;

/**
 *
 * @author KenweiVI
 */
import java.awt.Color;
import javax.swing.*;
import javax.swing.event.*;


public class CreateGroup extends javax.swing.JFrame implements CaretListener {

    
    JPanel jPanelGroupInfo;
    /**
     * Creates new form CreateGroups
     */
    public CreateGroup() {
        initComponents();
        jPanelGroupInfo = new JPanel();
        
        setLayout(null);
        jPanelGroupInfo.setBounds(200, 300, 1000, 800);
        jPanelGroupInfo.setOpaque(true);
        
        //uncomment to see dynamically created jpanel area
        //jPanelGroupInfo.setBackground(Color.CYAN);
        
        jTextFieldGroupSize.addCaretListener(this);
        
        add(jPanelGroupInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonHomePage = new javax.swing.JButton();
        jButtonSignOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldGroupSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanelINeedThisHereCuz = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 800));

        jButtonHomePage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonHomePage.setText("Home Page");
        jButtonHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomePageActionPerformed(evt);
            }
        });

        jButtonSignOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSignOut.setText("Signout");
        jButtonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignOutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Group Size:");

        jTextFieldGroupSize.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldGroupSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGroupSizeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("(Max 20)");

        javax.swing.GroupLayout jPanelINeedThisHereCuzLayout = new javax.swing.GroupLayout(jPanelINeedThisHereCuz);
        jPanelINeedThisHereCuz.setLayout(jPanelINeedThisHereCuzLayout);
        jPanelINeedThisHereCuzLayout.setHorizontalGroup(
            jPanelINeedThisHereCuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelINeedThisHereCuzLayout.setVerticalGroup(
            jPanelINeedThisHereCuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButtonSave.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHomePage)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSignOut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelINeedThisHereCuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldGroupSize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSave)
                        .addGap(306, 306, 306)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSignOut)
                    .addComponent(jButtonHomePage))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldGroupSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(34, 34, 34)
                .addComponent(jPanelINeedThisHereCuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 388, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Create A New Group userName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomePageActionPerformed
        // TODO add your handling code here:
        HomePage Info = new HomePage();
        dispose();
        Info.setVisible(true);
    }//GEN-LAST:event_jButtonHomePageActionPerformed

    private void jButtonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignOutActionPerformed
        // TODO add your handling code here:
        LoginWindow Info = new LoginWindow();
        dispose();
        Info.setVisible(true);
    }//GEN-LAST:event_jButtonSignOutActionPerformed

    private void jTextFieldGroupSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGroupSizeActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTextFieldGroupSizeActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHomePage;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelINeedThisHereCuz;
    private javax.swing.JTextField jTextFieldGroupSize;
    // End of variables declaration//GEN-END:variables

    @Override
    public void caretUpdate(CaretEvent e) {
        String groupSize = jTextFieldGroupSize.getText();
        
        jPanelGroupInfo.removeAll();
        
        if(!groupSize.equals("")) {
            int groupSizeInt = Integer.parseInt(groupSize);
            
            if (groupSizeInt <= 20 ) {                
                JLabel jlabelGroupName = new JLabel();
                JTextField jtextfieldGroupName = new JTextField();
                JLabel jlabels[] = new JLabel[groupSizeInt];                 
                JTextField jtextfields[] = new JTextField[groupSizeInt];
                
                
                jlabelGroupName.setText("Group Name: ");
                jlabelGroupName.setFont(new java.awt.Font("Tahoma", 1, 24));
                jlabelGroupName.setPreferredSize(new java.awt.Dimension(400, 40));
                jlabelGroupName.setHorizontalAlignment(JLabel.RIGHT);
                jPanelGroupInfo.add(jlabelGroupName);
                
                
                jtextfieldGroupName.setFont(new java.awt.Font("Tahoma", 1, 24));
                jtextfieldGroupName.setPreferredSize(new java.awt.Dimension(400, 40));
                jPanelGroupInfo.add(jtextfieldGroupName);
                for (int i = 0; i < jlabels.length; i++) {
                    jlabels[i] = new JLabel("Student" + i);
                    jlabels[i].setText("Student " + (i+1) + " ID#: ");
                    jlabels[i].setFont(new java.awt.Font("Tahoma", 1, 24));
                    jlabels[i].setPreferredSize(new java.awt.Dimension(200, 40));
                    jPanelGroupInfo.add(jlabels[i]);
                    
                    jtextfields[i] = new JTextField();
                    jtextfields[i].setFont(new java.awt.Font("Tahoma", 1, 24));
                    jtextfields[i].setPreferredSize(new java.awt.Dimension(200, 40));
                    jPanelGroupInfo.add(jtextfields[i]);
                }
            }
        }          
        jPanelGroupInfo.validate();
        jPanelGroupInfo.repaint();
    }
}
