/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PollingSystem;


/**
 *
 * @author KenweiVI
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonProfile = new javax.swing.JButton();
        jButtonSignOut = new javax.swing.JButton();
        jButtonNewGroup = new javax.swing.JButton();
        jButtonPollHistory = new javax.swing.JButton();
        jButtonNewPoll = new javax.swing.JButton();
        jButtonCurrentPolls = new javax.swing.JButton();
        jButtonCurrentGroup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 800));

        jButtonProfile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonProfile.setText("Profile");
        jButtonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfileActionPerformed(evt);
            }
        });

        jButtonSignOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSignOut.setText("Signout");
        jButtonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignOutActionPerformed(evt);
            }
        });

        jButtonNewGroup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonNewGroup.setText("Create New Group");
        jButtonNewGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGroupActionPerformed(evt);
            }
        });

        jButtonPollHistory.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonPollHistory.setText("Poll History");
        jButtonPollHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPollHistoryActionPerformed(evt);
            }
        });

        jButtonNewPoll.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonNewPoll.setText("Create New Poll");
        jButtonNewPoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPollActionPerformed(evt);
            }
        });

        jButtonCurrentPolls.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCurrentPolls.setText("Current Polls");
        jButtonCurrentPolls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCurrentPollsActionPerformed(evt);
            }
        });

        jButtonCurrentGroup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCurrentGroup.setText("Current Groups");
        jButtonCurrentGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCurrentGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonProfile)
                .addGap(18, 18, 18)
                .addComponent(jButtonSignOut)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewGroup)
                    .addComponent(jButtonCurrentPolls)
                    .addComponent(jButtonNewPoll)
                    .addComponent(jButtonPollHistory)
                    .addComponent(jButtonCurrentGroup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSignOut)
                    .addComponent(jButtonProfile))
                .addGap(44, 44, 44)
                .addComponent(jButtonNewGroup)
                .addGap(18, 18, 18)
                .addComponent(jButtonCurrentGroup)
                .addGap(18, 18, 18)
                .addComponent(jButtonNewPoll)
                .addGap(18, 18, 18)
                .addComponent(jButtonCurrentPolls)
                .addGap(18, 18, 18)
                .addComponent(jButtonPollHistory)
                .addGap(0, 316, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to UHD Polling userName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignOutActionPerformed
        // TODO add your handling code here:
        LoginWindow Info = new LoginWindow();
        dispose();
        Info.setVisible(true);
    }//GEN-LAST:event_jButtonSignOutActionPerformed

    private void jButtonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfileActionPerformed
        // TODO add your handling code here:
        UserProfile Info = new UserProfile();
        dispose();
        Info.setVisible(true);
    }//GEN-LAST:event_jButtonProfileActionPerformed

    private void jButtonCurrentGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCurrentGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCurrentGroupActionPerformed

    private void jButtonNewGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewGroupActionPerformed

    private void jButtonNewPollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewPollActionPerformed

    private void jButtonCurrentPollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCurrentPollsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCurrentPollsActionPerformed

    private void jButtonPollHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPollHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPollHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCurrentGroup;
    private javax.swing.JButton jButtonCurrentPolls;
    private javax.swing.JButton jButtonNewGroup;
    private javax.swing.JButton jButtonNewPoll;
    private javax.swing.JButton jButtonPollHistory;
    private javax.swing.JButton jButtonProfile;
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
