/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PollingSystem;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author KenweiVI
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */    
    public UserProfile() {
        initComponents();
        jPanelPasswordReset.setVisible(false);
        
        try {
            Scanner input2 = new Scanner(new File("userLogin.txt"));
            Scanner input = new Scanner(new File("UHD_DB.txt"));
            String employeeID = input2.nextLine();
            String userLastName = "userLastName";

            while (input.hasNextLine()) {
                String t = input.nextLine();
                String[] DB_array = t.split(";");

                if (employeeID.equals(DB_array[0])) {
                    userLastName = DB_array[3];
                    break;
                }
            }

            jLabelTitle.setText("Welcome to Your Profile " + userLastName + "!");
            jLabelEmployeeID.setText(employeeID);
            input2.close();
            input.close();

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null,
                    "University DB Not Found", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonHomePage = new javax.swing.JButton();
        jButtonSignOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelEmployeeID = new javax.swing.JLabel();
        jButtonChangePassword = new javax.swing.JButton();
        jPanelPasswordReset = new javax.swing.JPanel();
        jTextCurrentPassword = new javax.swing.JTextField();
        jTextNewPassword = new javax.swing.JTextField();
        jTextConfirmPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonPasswordSubmit = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 800));

        jButtonHomePage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonHomePage.setText("Hope Page");
        jButtonHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomePageActionPerformed(evt);
            }
        });

        jButtonSignOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSignOut.setText("Signout");
        jButtonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignOutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Employee ID:");

        jLabelEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButtonChangePassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonChangePassword.setText("Change Password");
        jButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswordActionPerformed(evt);
            }
        });

        jPanelPasswordReset.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanelPasswordResetComponentHidden(evt);
            }
        });

        jTextCurrentPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextCurrentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCurrentPasswordActionPerformed(evt);
            }
        });

        jTextNewPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNewPasswordActionPerformed(evt);
            }
        });

        jTextConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextConfirmPasswordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Current Password:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("New Password:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Confirm Password:");

        jButtonPasswordSubmit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonPasswordSubmit.setText("Submit");
        jButtonPasswordSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasswordSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPasswordResetLayout = new javax.swing.GroupLayout(jPanelPasswordReset);
        jPanelPasswordReset.setLayout(jPanelPasswordResetLayout);
        jPanelPasswordResetLayout.setHorizontalGroup(
            jPanelPasswordResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasswordResetLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelPasswordResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPasswordSubmit)
                    .addGroup(jPanelPasswordResetLayout.createSequentialGroup()
                        .addGroup(jPanelPasswordResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPasswordResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelPasswordResetLayout.setVerticalGroup(
            jPanelPasswordResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasswordResetLayout.createSequentialGroup()
                .addGroup(jPanelPasswordResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanelPasswordResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanelPasswordResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButtonPasswordSubmit)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHomePage)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSignOut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonChangePassword)
                            .addComponent(jPanelPasswordReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 357, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSignOut)
                    .addComponent(jButtonHomePage))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jButtonChangePassword)
                .addGap(18, 18, 18)
                .addComponent(jPanelPasswordReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setText("Welcome to Your Profile userName!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabelTitle)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomePageActionPerformed
        // TODO add your handling code here:        
        HomePage Info = new HomePage();
        dispose();
        Info.setVisible(true);
    }//GEN-LAST:event_jButtonHomePageActionPerformed

    private void jButtonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignOutActionPerformed
        // TODO add your handling code here:
        LoginWindow Info = new LoginWindow();
        dispose();
        Info.setVisible(true);
    }//GEN-LAST:event_jButtonSignOutActionPerformed

    private void jButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswordActionPerformed
        // TODO add your handling code here:
        jPanelPasswordReset.setVisible(true);
    }//GEN-LAST:event_jButtonChangePasswordActionPerformed

    private void jTextCurrentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCurrentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCurrentPasswordActionPerformed

    private void jTextNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewPasswordActionPerformed

    private void jTextConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextConfirmPasswordActionPerformed

    private void jPanelPasswordResetComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelPasswordResetComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelPasswordResetComponentHidden

    private void jButtonPasswordSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasswordSubmitActionPerformed
        // TODO add your handling code here:
        String currentPassword = jTextCurrentPassword.getText();
        String newPassword = jTextNewPassword.getText();
        String passwordConfirm = jTextConfirmPassword.getText();
        String currentPasswordConfirm = "default";
                
        try {
            Scanner input20 = new Scanner(new File("userLogin.txt"));
            Scanner input0 = new Scanner(new File("UHD_DB.txt"));
            String employeeID = input20.nextLine();

            while (input0.hasNextLine()) {
                String t = input0.nextLine();
                String[] DB_array = t.split(";");

                if (employeeID.equals(DB_array[0])) {
                    currentPasswordConfirm = DB_array[2];
                    break;
                }
            }

            input20.close();
            input0.close();

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null,
                    "University DB Not Found", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        if (newPassword.equals(passwordConfirm) && newPassword.length() >= 8 && currentPassword.equals(currentPasswordConfirm)) {
            
            
            
            
            
            
            try {
                FileWriter input2 = new FileWriter("pollHistoryTemp.txt", false);
                BufferedWriter input3 = new BufferedWriter(input2);
                Scanner input = new Scanner(new File("userLogin.txt"));
                Scanner input4 = new Scanner(new File("UHD_DB.txt"));
                String userName = input.nextLine();
                int g = 0;

                while (input4.hasNextLine()) {
                    String t = input4.nextLine();
                    String[] DB_array = t.split(";");

                    //System.out.println(DB_array[0]);
                    if (userName.equals(DB_array[0])) {
                        //here is where I print all the stuffs
                        input3.write(DB_array[0] + ";" + DB_array[1] + ";" + newPassword + ";" + DB_array[3] + ";");
                        input3.newLine();
                    } else {
                        input3.write(t);
                        input3.newLine();
                    }
                }
                input3.flush();
                input4.close();
                input3.close();
                input2.close();
                input.close();

                FileWriter input5 = new FileWriter("UHD_DB.txt", false);
                BufferedWriter input6 = new BufferedWriter(input5);
                Scanner input7 = new Scanner(new File("pollHistoryTemp.txt"));
                while (input7.hasNextLine()) {
                    String t = input7.nextLine();
                    input6.write(t);
                    input6.newLine();

                }
                input6.flush();
                input7.close();
                input6.close();
                input5.close();
                
                StudentPortal Info = new StudentPortal();
                dispose();
                Info.setVisible(true);
            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(null,
                        "University DB Not Found", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(CreateGroup.class.getName()).log(Level.SEVERE, null, ex);
            }            
            
        }
        else if (newPassword.length() < 8){
            //error message
            JOptionPane.showMessageDialog(null, "Invalid Login Details: Passwords Must Be At Least Eight Characters Long.", "Login Error", JOptionPane.ERROR_MESSAGE);
//            jTextNewPassword.setText(null);
//            jTextConfirmPassword.setText(null);
        }
        else if (!newPassword.equals(passwordConfirm)) {            
            JOptionPane.showMessageDialog(null, "Invalid Login Details: Confirm Password Does Not Match.", "Login Error", JOptionPane.ERROR_MESSAGE);

        }
        else if (!currentPassword.equals(currentPasswordConfirm)) {           
            JOptionPane.showMessageDialog(null, "Invalid Login Details: Current Password Does Not Match.", "Login Error", JOptionPane.ERROR_MESSAGE);
           
        } 
        else {           
            JOptionPane.showMessageDialog(null, "Invalid Login Details: An Unknown Error Occured.", "Login Error", JOptionPane.ERROR_MESSAGE);
 
            
        }
    }//GEN-LAST:event_jButtonPasswordSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangePassword;
    private javax.swing.JButton jButtonHomePage;
    private javax.swing.JButton jButtonPasswordSubmit;
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPasswordReset;
    private javax.swing.JTextField jTextConfirmPassword;
    private javax.swing.JTextField jTextCurrentPassword;
    private javax.swing.JTextField jTextNewPassword;
    // End of variables declaration//GEN-END:variables
}
